export const metadata = {
    title: "Terms and conditions",
    description: "Generated by create next app",
  };
const TermsPage = () => {
    return (
        <div>
            Terms and conditions
        </div>
    );
};

export default TermsPage;